#!/usr/bin/env python3
import sys
import json
from cromwell_rest_api import CromwellRestAPI


def main():
    # Using old Caper's subworkflow embedding module
    workflow_id = sys.argv[1]
    api = CromwellRestAPI()
    j = api.get_metadata([workflow_id], embed_subworkflow=True)
    print(json.dumps(j[0], indent=4))


if __name__ == "__main__":
    main()

